### ISSUE TITLE
make setup fails

### ISSUE THREAD

**Issue by vijayank88** [efabless/caravel_user_project#152]
Description:

I am trying to follow quick start guide: https://github.com/efabless/caravel_user_project/blob/main/docs/source/quickstart.rst
With `make setup` failed with following errors:
OS: Centos 7

```
Installing collected packages: pcpp, volare, colorama, certifi, urllib3
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 854, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 492, in move_wheel_files
    maker.make_multiple(['%s = %s' % kv for kv in console.items()])
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distlib/scripts.py", line 383, in make_multiple
    filenames.extend(self.make(specification, options))
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distlib/scripts.py", line 372, in make
    self._make_script(entry, filenames, options=options)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distlib/scripts.py", line 276, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distlib/scripts.py", line 250, in _write_script
    self._fileop.write_binary_file(outname, script_bytes)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distlib/util.py", line 407, in write_binary_file
    with open(path, 'wb') as f:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/pcpp'
make[1]: *** [install-volare] Error 2
make[1]: Leaving directory `/home/vijayan/CARAVEL_FLOW/RISCV_Based_BMS'
make: *** [pdk-with-volare] Error 2
```

Expectation:
`make setup` should complete without any errors.

**Comment by vijayank88** [comment]
There was issue with accessing volare.

Re-installed volate with `python3 -m pip install --user --upgrade --no-cache-dir volare`

Manually installed `openlane` and `pdks` with following steps:

`make openlane`
`make pdk-with-volare`
