### ISSUE TITLE
DRC Klayout pin label purposes overlapping drawing crashing

### ISSUE THREAD

**Issue by m-usama-z** [efabless/caravel_user_project#170]
I'm using Innovus to create a GDS. The DRC check "Klayout pin label purposes overlapping drawing" kept crashing while saying that "report-file.xml" not found, which it is supposed to create. I was able to get around it by creating an empty file at the report file's location before the check started, then the check passed. Kindly check this check's DRC script.

**Comment by m-usama-z** [comment]
Log:

`cd /home/uetlhr/mpw_precheck && \
docker run -v /home/uetlhr/mpw_precheck:/home/uetlhr/mpw_precheck \
-v /home/uetlhr/Documents/SermoPlot_backend/draft_SRAM/drc/caravel_user_project:/home/uetlhr/Documents/SermoPlot_backend/draft_SRAM/drc/caravel_user_project \
-v /mnt/Cadence/PDK/pdk_skywater_test:/mnt/Cadence/PDK/pdk_skywater_test \
-e INPUT_DIRECTORY=/home/uetlhr/Documents/SermoPlot_backend/draft_SRAM/drc/caravel_user_project \
-e PDK_PATH=/mnt/Cadence/PDK/pdk_skywater_test/sky130A \
-e PDK_ROOT=/mnt/Cadence/PDK/pdk_skywater_test \
-e PDKPATH=/mnt/Cadence/PDK/pdk_skywater_test/sky130A \
-u 1000:1000 \
efabless/mpw_precheck:latest bash -c "cd /home/uetlhr/mpw_precheck ; python3 mpw_precheck.py --input_directory /home/uetlhr/Documents/SermoPlot_backend/draft_SRAM/drc/caravel_user_project --pdk_path /mnt/Cadence/PDK/pdk_skywater_test/sky130A"
{{EXTRACTING FILES}} Extracting compressed files in: /home/uetlhr/Documents/SermoPlot_backend/draft_SRAM/drc/caravel_user_project
{{Project Type Info}} digital
{{Project GDS Info}} user_project_wrapper: 4d9df6dba27f086ca00de5be35adace8b65e067a
{{Tools Info}} KLayout: v0.27.10 | Magic: v8.3.315
{{PDKs Info}} PDK: sky130A | Open PDKs: a1cf1b7c41dfccf1d38815278c543dd2f1e402dc | Skywater PDK: ea95157faad3a3f5c560aaec3f1841ee5a2aa2db
{{START}} Precheck Started, the full log 'precheck.log' will be located in '/home/uetlhr/Documents/SermoPlot_backend/draft_SRAM/drc/caravel_user_project/precheck_results/14_OCT_2022___03_24_54/logs'
{{PRECHECK SEQUENCE}} Precheck will run the following checks: [Klayout Pin Label Purposes Overlapping Drawing, Klayout Metal Minimum Clear Area Density]
{{STEP UPDATE}} Executing Check 1 of 2: Klayout Pin Label Purposes Overlapping Drawing
Traceback (most recent call last):
  File "mpw_precheck.py", line 139, in <module>
    default_content='_default_content')
  File "mpw_precheck.py", line 100, in main
    run_precheck_sequence(precheck_config=precheck_config, project_config=project_config)
  File "mpw_precheck.py", line 68, in run_precheck_sequence
    results[check.__surname__] = check.run()
  File "/home/uetlhr/mpw_precheck/check_manager/__init__.py", line 130, in run
    self.klayout_cmd_extra_args)
  File "/home/uetlhr/mpw_precheck/checks/drc_checks/klayout/klayout_gds_drc_check.py", line 19, in klayout_gds_drc_check
    with open(report_file_path) as klayout_xml_report:
FileNotFoundError: [Errno 2] No such file or directory: '/home/uetlhr/Documents/SermoPlot_backend/draft_SRAM/drc/caravel_user_project/precheck_results/14_OCT_2022___03_24_54/outputs/reports/klayout_pin_label_purposes_overlapping_drawing_check.xml'
make: *** [Makefile:186: run-precheck] Error 1
`

**Comment by m-usama-z** [comment]
Sorry, the checker expects the top cell name to be 'user_project_wrapper', mine was different :)
