### ISSUE TITLE
run-precheck fails 

### ISSUE THREAD

**Issue by abdullahyildiz** [efabless/caravel_user_project#202]
`make run-precheck` on [Caravel User Project Release mpw-7g](https://github.com/efabless/caravel_user_project/tree/mpw-7g) fails with the following error:

```
{{STEP UPDATE}} Executing Check 9 of 14: Klayout FEOL
Generating LALR tables
WARNING: 183 shift/reduce conflicts
Traceback (most recent call last):
  File "mpw_precheck.py", line 141, in <module>
    default_content='_default_content')
  File "mpw_precheck.py", line 102, in main
    run_precheck_sequence(precheck_config=precheck_config, project_config=project_config)
  File "mpw_precheck.py", line 68, in run_precheck_sequence
    results[check.__surname__] = check.run()
  File "/home/ayildiz/mpw_precheck/check_manager/__init__.py", line 156, in run
    self.klayout_cmd_extra_args)
  File "/home/ayildiz/mpw_precheck/checks/drc_checks/klayout/klayout_gds_drc_check.py", line 20, in klayout_gds_drc_check
    with open(report_file_path) as klayout_xml_report:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ayildiz/work/efabless/caravel_user_project/precheck_results/19_NOV_2022___20_07_23/outputs/reports/klayout_feol_check.xml'
Makefile:221: recipe for target 'run-precheck' failed
make: *** [run-precheck] Error 1
```

**Comment by m-usama-z** [comment]
It's because mpw_precheck is missing "mpw_precheck/checks/tech-files/sky130B_mr.drc". I've opened an issue in mpw_precheck's repo.

**Comment by m-usama-z** [comment]
I just saw a message in slack, saying that MPW-7 will use sky130A.
