### ISSUE TITLE
run-precheck fails on README.md

### ISSUE THREAD

**Issue by mguthaus** [efabless/caravel_user_project#28]
If you run the precheck on the default design, it fails like this:

```
mrg@diode ~/data/caravel_user_project ((HEAD detached at mpw-two-c))$ make run-precheck 
cd /home/mrg/open_mpw_precheck && \
docker run -v /home/mrg/open_mpw_precheck:/usr/local/bin -v /home/mrg/data/caravel_user_project:/home/mrg/data/caravel_user_project -v /software/PDKs:/software/PDKs -v /home/mrg/data/caravel_user_project/caravel:/home/mrg/data/caravel_user_project/caravel \
-u 1000:1000 efabless/open_mpw_precheck:latest bash -c "python3 open_mpw_prechecker.py --pdk_root /software/PDKs --target_path /home/mrg/data/caravel_user_project -rfc -c /home/mrg/data/caravel_user_project/caravel "
{{PROGRESS}} Executing Step 0 of 8: Extracting GDS Files
{{PROGRESS}} Executing Step 1 of 8: Project License Check
{{WARNING}} SPDX COMPLIANCE Found 22 non-compliant files with the SPDX Standard. Check full log for more information
{{PROGRESS}} Executing Step 2 of 8: YAML File Check
{{PROGRESS}} YAML file valid!
Step 2 done without fatal errors.
{{PROGRESS}} Detected Project Type is "digital"
{{PROGRESS}} Executing Step 3 of 8: Project Compliance Checks
{{PROGRESS}} Manifest Checks Passed. Caravel Version Matches.
{{PROGRESS}} Makefile Checks Passed.
{{WARNING}} Default README.md checks failed because: Could not open file None/README.md
Traceback (most recent call last):
  File "/usr/local/bin/base_checks/check_defaults.py", line 69, in has_empty_documentation
    with open('%s/README.md'%target_path, 'r') as readme:
FileNotFoundError: [Errno 2] No such file or directory: 'None/README.md'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "open_mpw_prechecker.py", line 363, in <module>
    run_check_sequence(target_path, caravel_root, pdk_root, output_directory, run_fuzzy_checks, run_gds_fc, skip_drc, skip_xor, drc_only, dont_compress, manifest_source, run_klayout_drc, run_klayout_fom_density_check, private)
  File "open_mpw_prechecker.py", line 200, in run_check_sequence
    empty_documentation, reason = check_defaults.has_empty_documentation()
  File "/usr/local/bin/base_checks/check_defaults.py", line 82, in has_empty_documentation
    errors +=  "\nCould not open %s/README.md"%directory
NameError: name 'directory' is not defined
make: *** [Makefile:146: run-precheck] Error 1
mrg@diode ~/data/caravel_user_project ((HEAD detached at mpw-two-c))$ 
```

**Comment by a-omla** [comment]
@mguthaus I will be closing this issue as it is not longer relevant to the current codebase, if the issue still persists please open a new issue, hope you understand 🙏
